kind: pipeline 
type: docker 
name: CI

trigger:
  event:
    - push

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - name: docs
        path: /docs
    commands: 
      - ls
      - dotnet restore DevGardenAPI.sln
      - dotnet build DevGardenAPI.sln -c Debug --no-restore
      - dotnet publish DevGardenAPI.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release

  - name: hadolint-check
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint ./Dockerfile
    depends_on: [build]

  - name: docker-build-and-push
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      context: .
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/lou.broda/devgardenapi
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD
    depends_on: [hadolint-check]

  - name: deploy-container
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: hub.codefirst.iut.uca.fr/lou.broda/devgardenapi:latest
      CONTAINERNAME: devgardenapi
      COMMAND: create
      OVERWRITE: true
      ADMINS: nicolasfranco,loubroda,timlevadoux,brunoda_costa_cunha
    depends_on: [docker-build-and-push]

  # database container deployment
  - name: deploy-container-mysql
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: mysql:latest
        CONTAINERNAME: DevGarden-mysql
        COMMAND: create
        PRIVATE: true
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_ROOT_PASSWORD:
          from_secret: db_root_password
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_DATABASE:
          from_secret: db_database
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_USER:
          from_secret: db_user
        CODEFIRST_CLIENTDRONE_ENV_MYSQL_PASSWORD:
          from_secret: db_password
        ADMINS : nicolasfranco,brunoda_costa_cunha,loubroda,timlevadoux
