kind: pipeline 
type: docker 
name: CI
 
trigger:
	event:
		- push

steps:
	- name: build
		 image: mcr.microsoft.com/dotnet/sdk:7.0
		 volumes:
			 - name: docs
				 path: /docs
		 commands: 
			 - ls
			 - dotnet restore DevGardenAPI.sln
			 - dotnet build DevGardenAPI.sln -c Debug --no-restore
			 - dotnet publish DevGardenAPI.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release

	- name: hadolint-check
		image: hadolint/hadolint:latest-debian
		commands:
			- hadolint Sources/Dockerfile
		depends_on: [build]

	- name: docker-build-and-push
		image: plugins/docker
		settings:
			dockerfile: Sources/Dockerfile
			context: Sources
			registry: hub.codefirst.iut.uca.fr
			repo: hub.codefirst.iut.uca.fr/devgarden/devgardenapi
			username:         
				from_secret: SECRET_REGISTRY_USERNAME       
			password:         
				from_secret: SECRET_REGISTRY_PASSWORD
		depends_on: [hadolint-check]

	- name: deploy-container
		image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
		environment:
			IMAGENAME: hub.codefirst.iut.uca.fr/devgarden/devgardenapi:latest
			CONTAINERNAME: devgardenapi
			COMMAND: create
			OVERWRITE: true
			ADMINS: nicolasfranco,loubroda,timlevadoux,brunoda_costa_cunha
		depends_on: [docker-build-and-push]
	
